---
keys:
  # Personal SSH
  - &admin_maxwellbrown age1usc2072gec0plj2q866m0uyeh2rly60xnxts4c3xxh50cwygte8s8avj8a
  - &admin_mikearnaldi age15umcap7zkzq5g32zykcywjk0l6cwldxqk7e46t2ynkkwy0eghuas5rs6t7
creation_rules:
  - encrypted_regex: ^(data|stringData)$
    path_regex: infra/.*/secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *admin_maxwellbrown
          - *admin_mikearnaldi
...
