---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-registry-credentials
data:
  .dockerconfigjson: ENC[AES256_GCM,data:DEU1LMpetS5fnu4wVXVeMzDuxRPcgCGAh1dH69F3f34gaw5D22sM9Dn3cd+d84wWVJyNsLcKRn3PvZ+CNq3qhvGaovElB09jXR44lOtDpCljUh247Jbm7Hgrj4N/alZzOjXMfaQIqB5yhub0A6CSfbDwDrnHc+MqB4TpDb8EPeHL/XKGNyNcYkNnqsYGMPNRPwDMUQ382+1999pz5EDt5inQf5sK/mhCGpxzfrc4fO6HWdRPUwL5zU/r8K/sVOY9Yc8XxDt+lPP/Kuj91R1PFwvdUA4/xL5kciymFOgpyBgzdaHzCfbGjEG1kMyPSfkT5cNbwYmOy84xIvUde05F2wHNmxvE39CfxcLWZ0DX/vbdnUimogz3hLMsjaRN0DDYvqexxw==,iv:cgqcz2ivHSQDZh8HvsKKmgbrbJWfjxcM18HSHMPQJo8=,tag:fyGCLYmD7g2zO3FOhJqvQw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1usc2072gec0plj2q866m0uyeh2rly60xnxts4c3xxh50cwygte8s8avj8a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYTYxRlVUTXU3enNtbnlZ
        R2JKUGtXV25YTHVHc09wa0dldFdvN1pPb2hRCm56RllqRDAreUs0UWJreGZxYXdm
        dW9OSTYvVHBRcXJ6YVhabEdwZFlvRGMKLS0tIFBhV1ZNNk44SkZzZmR6Wnd6ZzVx
        RThCM3UzUEJ5cXdWS1RFVFdvY1o3bTQKc5t4juFsxVN0yOGm8ygHj7/ax+sjag6b
        hGXfgD6tMlaQcPn5JYB5f6eOpEi6T7EIbi3nfLOn8vtpLR88ZIz0fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-03-27T00:05:02Z'
  mac: ENC[AES256_GCM,data:0qP8A+rKvMKZKDff/BRqptIVo6uOINHKyHd1HnqIn7OLUwKcmcjY9G3G0V1P+VLOnxvbYgEcDKSy0t0xJE1gvXxviD/fER3MP5Fzy4m6H0aiABv2huM2MBT0bB5MrOElDLcAbEEZWfwYI2iDczvS7zCOA6Ba/YjX8dWVtji+cec=,iv:/fvM3luRFkthJxZZWaa9Dk+aRfYP3zy5l00RpB/HCZc=,tag:AnmhoJ8/swV9hUHO3YGGDQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
...
