---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: effect-website

resources:
  - ../../base
  - ./resources/deployment.yaml
  - ./resources/ingress.yaml
  - ./resources/origin-issuer.yaml
  - ./resources/secrets.yaml
  - ./resources/service.yaml

commonLabels:
  app: effect-website
  variant: prod
