---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./generators/secrets-generator.yaml

resources:
  - ../../base

namespace: effect-website

commonLabels:
  app: effect-website
  variant: prod
...
